### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [nasa/koviz#10]
Would you like to add more error handling for return values from functions like the following?
* [fprintf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output") ⇒ [main](https://github.com/nasa/koviz/blob/7fa6c11fadafeea5cf2fa09929932deaf3721310/koviz/main.cpp#L316)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [create_bw_low_pass_filter](https://github.com/nasa/koviz/blob/e2774be423ed97217c67f84926e3f34bcddfe7ae/libkoviz/filter.c#L57)

**Comment by keithvetter** [comment]
I don't want to check the error code of fprintf().  The low pass filter code is actually not mine.  I credited it at top.  I can see checking malloc().  Well, this sort of code cleanup is something I'd like to do later in life after I retire.

**Comment by elfring** [comment]
* :thinking: How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by elfring** [comment]
>…, but not sure how I'd use those ideas to benefit koviz.

:thinking: Can you become more aware that [error detection](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Documentation") belongs to known cross-cutting concerns?

**Comment by keithvetter** [comment]
Can you give me another article that shows how error detection helps cross-cutting concerns?  Do you mean, for instance, that if I don't want to check the return code for every printf(), that I should wrap the printf() in some error log utility?  Checking the return code of a printf() just seems like overkill that would clutter the code.

**Comment by elfring** [comment]
:thought_balloon: I propose to take also the possibility better into account for data output failures.

:eyes: [Some development approaches are worth for another look](https://www.aspectc.org/ "Software development with AspectC++"), aren't they?
