### ISSUE TITLE
qmake-qt5 command is not found, Ubuntu 20.04

### ISSUE THREAD

**Issue by AdvaitDhingra** [nasa/koviz#4]
When running the install command (on Ubuntu 20.04 LTS)

```
qmake-qt5
```
I get the error:
```
qmake-qt5: command not found
```
This is even after entering
```
sudo apt-get install qtbase5-dev
```
Is the install command wrong, or is the qmake command not correct for Ubuntu

**Comment by keithvetter** [comment]
Advait,
I run on CentOS7.  I'll ask somebody that uses Ubuntu.  Maybe something has
changed with Ubuntu 20.  Not sure.
Keith

**Comment by keithvetter** [comment]
This link may help: https://www.linux.org/threads/qmake-not-found.23766/

See if this exists:  /usr/lib/qt5/bin/qmake

**Comment by AdvaitDhingra** [comment]
> See if this exists: /usr/lib/qt5/bin/qmake
No such path exists. I tired all the install commands the website stated.

**Comment by keithvetter** [comment]
I sent a koviz Ubuntu user an email.  I think that he uses Ubuntu 18, so may not help, but we'll see.

As a code hobbyist, I think Qt is a good thing to learn, so hopefully you can get Qt working.  Qt is koviz' only dependency, but a big one.  I'm very unfamiliar with the way Ubuntu packages things, so am little help myself.

**Comment by keithvetter** [comment]
You might try:
% sudo updatedb
% locate qmake

**Comment by AdvaitDhingra** [comment]
> You might try:
> 
> % sudo updatedb
> 
> % locate qmake

Thanks, I'll try this

**Comment by AdvaitDhingra** [comment]
I found the qt5 file in the /usr/lib direcotry. What can I do from here? The forum said i should run a file named ./config but I see no such file

**Comment by keithvetter** [comment]
When you say, "I found the qt5 file", do you mean you found "qmake".

After asking around, I heard, "I think it's just qmake on Ubuntu 20.04.  In past Ubuntu(s), you could have both qt4 and qt5 qmake installed and you set  which one was "qmake" by installing the correct "default" qmake or qt4/5 package.  And I think the qmake-qt5 and qmake-qt4 could ve explicitly called.  I guess not now."

You're the guinea pig, Advait.

**Comment by AdvaitDhingra** [comment]
> When you say, "I found the qt5 file", do you mean you found "qmake".
> 
> After asking around, I heard, "I think it's just qmake on Ubuntu 20.04. In past Ubuntu(s), you could have both qt4 and qt5 qmake installed and you set which one was "qmake" by installing the correct "default" qmake or qt4/5 package. And I think the qmake-qt5 and qmake-qt4 could ve explicitly called. I guess not now."

 Okay, I'll keep looking for a solution. Thanks for the tips

> You're the guinea pig, Advait.

 :D

**Comment by keithvetter** [comment]
I spoke with a Ubuntu 20.04 koviz user.  He suggested:

% apt install qtchooser

I hope qtchooser is the ticket.

**Comment by AdvaitDhingra** [comment]
> I spoke with a Ubuntu 20.04 koviz user. He suggested:
> 
> % apt install qtchooser
> 
> I hope qtchooser is the ticket.

Okay, I'll try that, I have one question. Do I need to install kviz in a specific directory, or does anything work? Because when I run qmake, it says that the current install path is /usr/local. Do i need to git clone in there?

**Comment by keithvetter** [comment]
Oh, if you have qmake, you're there.

It's only an install path that you can set if you like.  I never install it.  You can clone it to whatever directory you like.  When you build, the executable will go in a bin directory.

For example, this should work:
% cd ~/dev
% git clone <koviz-repo>
% cd koviz
% qmake
% make
% bin/koviz -h

**Comment by AdvaitDhingra** [comment]
Okay, it took a few extra steps but I think it's working now. I'll add the extra steps to the pr i made

**Comment by AdvaitDhingra** [comment]
I had to install flex

**Comment by keithvetter** [comment]
I'm surprised that flex is not rolled into Qt.  It is for my CentOS distro, I think.  That'd be great if you could add the steps.

**Comment by AdvaitDhingra** [comment]
Okay, now everything works when I enter bin/koviz -h but the kovz file has some weird charcters in it and I cant run koviz by itself in the command line

**Comment by AdvaitDhingra** [comment]
It's a bunch of question mark symbols and the file is unsupported.

**Comment by keithvetter** [comment]
Do you have a koviz executable?  I'll show you my commandline:

[(master) koviz]$ pwd
/home/kvetter/dev/koviz
[(master) koviz]$ ls
bin  build  docs  koviz  koviz.pri  koviz.pro  koviz.pro.user  lib  libkoviz  LICENSE  Makefile  README
[(master) koviz]$ ls -al bin/
total 1668
drwxrwxr-x 2 kvetter kvetter      19 Feb 16 12:37 .
drwxrwxr-x 9 kvetter kvetter    4096 Feb 11 15:06 ..
-rwxrwxr-x 1 kvetter kvetter 1696032 Feb 12 15:02 koviz

**Comment by AdvaitDhingra** [comment]
My bin folder only has 1 file named koviz that has those weird characters. This is my command line:

```
$ pwd
/home/advait/dev/koviz
$ ls
bin    docs   koviz.pri  lib       LICENSE   README
build  koviz  koviz.pro  libkoviz  Makefile
$ ls -al bin/
ls -al
total 1780
drwxrwxr-x 2 advait advait    4096 Feb 16 19:23 .
drwxrwxr-x 9 advait advait    4096 Feb 16 19:23 ..
-rwxrwxr-x 1 advait advait 1814304 Feb 16 19:23 koviz
```

There is no executable

**Comment by keithvetter** [comment]
If I understand, the koviz file that has weird characters because it is binary.  That 1814304 byte koviz file *is* the executable.  You should be able to run it:

My commandline:
% cd /home/kvetter/dev/koviz/bin
% ./koviz
koviz [error] : no RUNs specified.

**Comment by AdvaitDhingra** [comment]
Ohh ok

**Comment by AdvaitDhingra** [comment]
Oh yes, it's working now. What RUNs do I need to specify?

**Comment by keithvetter** [comment]
That is a loaded question.  RUNs normally come from Trick simulations.  Can you unzip the following?:

[SET_ball.zip](https://github.com/nasa/koviz/files/5991165/SET_ball.zip)

**Comment by AdvaitDhingra** [comment]
Yes, it*s working! Thanks, i'll close this issue.

**Comment by keithvetter** [comment]
That's great.  You should be able to:
% unzip SET_ball.zip
% koviz SET_ball/RUN*

Thank you too.  This will help me help other Ubuntu users.

**Comment by keithvetter** [comment]
I attached a screenshot of a koviz plot:

[koviz-spring-plot.pdf](https://github.com/nasa/koviz/files/5991396/koviz-spring-plot.pdf)

**Comment by AdvaitDhingra** [comment]
I have to enter ./koviz SET_ball/RUN* and I get this: 

![Screenshot from 2021-02-16 21-25-54](https://user-images.githubusercontent.com/62119114/108117798-b55ed700-709d-11eb-8478-534e9463958a.png)

**Comment by keithvetter** [comment]
That's it.  You have a koviz plot.  That's the states of an orbiting ball.  Each curve is in a different simulation "RUN".

I have a bash alias which is close to:
alias kv="~/dev/koviz/bin/koviz"

Most, I'm guessing, put koviz in there $PATH.

Try the attached:

[states.zip](https://github.com/nasa/koviz/files/5991545/states.zip)

**Comment by AdvaitDhingra** [comment]
Yep, it's working. I can see the plots

**Comment by AdvaitDhingra** [comment]
I'll add the alias aswell

**Comment by keithvetter** [comment]
To develop, I use QtCreator.  It is a powerful IDE that ties the Qt help and libraries to your code development.  I highly recommend it for any C++ development.  I attached a screenshot.

![koviz-qtcreator](https://user-images.githubusercontent.com/1434444/108120612-2a62ea00-7067-11eb-81c9-9d80f41f0f6a.jpg)

**Comment by AdvaitDhingra** [comment]
> To develop, I use QtCreator. It is a powerful IDE that ties the Qt help and libraries to your code development. I highly recommend it for any C++ development. I attached a screenshot.
> 
> ![koviz-qtcreator](https://user-images.githubusercontent.com/1434444/108120612-2a62ea00-7067-11eb-81c9-9d80f41f0f6a.jpg)

I'll install it 👍🏼

**Comment by AdvaitDhingra** [comment]
I added the koviz alias and it seems to be working. How did you get your plot to look like a ball? It looks really cool.

**Comment by keithvetter** [comment]
That was a plot with different data.  That plot is hard to explain, but I used koviz "groups", styles, color, background, foreground etc.  Try the following with your ball data:

% kv DP_advait.txt SET_ball/RUN*

Then click on the y-axis-label of the xy plot, then click a curve.

[DP_advait.txt](https://github.com/nasa/koviz/files/5991644/DP_advait.txt)

**Comment by AdvaitDhingra** [comment]
> That was a plot with different data. That plot is hard to explain, but I used koviz "groups", styles, color, background, foreground etc. Try the following with your ball data:
> 
> % kv DP_advait.txt SET_ball/RUN*
> 
> Then click on the y-axis-label of the xy plot, then click a curve.
> 
> [DP_advait.txt](https://github.com/nasa/koviz/files/5991644/DP_advait.txt)

Okay, I'll do this. I'm thinking of making a install.sh script to automate this whole process. Would that be something useful?

**Comment by keithvetter** [comment]
I'm not sure if an install.sh would work.  That is why I left it to a README - with me on the other end to help as I can.  It's really a question of Qt (but then there was flex!)  There are mac users too.  An install.sh would have to be maintained.  There is also Windows.  

The most useful thing, for me, especially for Windows, would be a package that I could just give to somebody.  The problem with packaging is that it is just another thing to do.  That's why yum and apt exist.

You don't happen to work with Windows as well as Linux?

**Comment by AdvaitDhingra** [comment]
> You don't happen to work with Windows as well as Linux?

I have windows 10 and Ubuntu dual-booted 😅 

And I can make an if statement that detects the OS and runs the appropriate commands.

**Comment by keithvetter** [comment]
If I had a way to make a Windows koviz binary, a lot of people would be happy including myself :)  I'm not thinking so much about building it as I am giving a binary bonified Windows package with all the necessary *.dlls included so no work is needed for Windows users.  That is actually on my plate todo, just haven't gotten to it.  I only run on Linux.

**Comment by AdvaitDhingra** [comment]
Do you have discord? It would be easier to talk there than here
