### ISSUE TITLE
koviz on macOS

### ISSUE THREAD

**Issue by spfennell** [nasa/koviz#5]
I know koviz doesn't officially support macOS yet, but I thought I'd start a thread here.

Cross-posted from Trick issue board. 

QTCreator with all default settings does not build Koviz without a hitch.
Qt Creator version:
Qt Creator 4.14.2
Based on Qt 5.15.2 (Clang 11.0 (Apple), 64 bit)
Built on Mar 19 2021 09:03:22
From revision c34b950227
Errors

```

/Users/sfennell/koviz/libkoviz/dp.h:224: error: field has incomplete type 'QRectF'
In file included from ../../koviz/libkoviz/dp.cpp:1:
../../koviz/libkoviz/dp.h:224:12: error: field has incomplete type 'QRectF'
    QRectF _rect;
           ^
/Users/sfennell/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qmetatype.h:2089:1: note: forward declaration of 'QRectF'
QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
^
/Users/sfennell/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qmetatype.h:124:19: note: expanded from macro 'QT_FOR_EACH_STATIC_CORE_CLASS'
    F(QRectF, 20, QRectF) \
                  ^
```

```
/Users/sfennell/koviz/libkoviz/dp.cpp:566: error: incomplete result type 'QRectF' in function definition
../../koviz/libkoviz/dp.cpp:566:16: error: incomplete result type 'QRectF' in function definition
QRectF DPPlot::rect() const
               ^
/Users/sfennell/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qmetatype.h:2089:1: note: forward declaration of 'QRectF'
QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
^
/Users/sfennell/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qmetatype.h:124:19: note: expanded from macro 'QT_FOR_EACH_STATIC_CORE_CLASS'
    F(QRectF, 20, QRectF) \
                  ^
```

```
/Users/sfennell/koviz/libkoviz/dp.cpp:566: error: incomplete result type 'QRectF' in function definition
../../koviz/libkoviz/dp.cpp:566:16: error: incomplete result type 'QRectF' in function definition
QRectF DPPlot::rect() const
               ^
/Users/sfennell/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qmetatype.h:2089:1: note: forward declaration of 'QRectF'
QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
^
/Users/sfennell/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qmetatype.h:124:19: note: expanded from macro 'QT_FOR_EACH_STATIC_CORE_CLASS'
    F(QRectF, 20, QRectF) \
                  ^

```
```
:-1: error: [../../koviz/build/libkoviz/obj/dp.o] Error 1
```

**Comment by spfennell** [comment]
Success! And in dark mode too! 
<img width="1298" alt="koviz_on_mac" src="https://user-images.githubusercontent.com/19922011/117075947-43407a80-acfb-11eb-82e3-989fc84a97dc.png">

**Comment by spfennell** [comment]
Steps: 

Install QTCreator on mac with Qt. This may require configuring XCode, command line tools, and clang (mine were already configured from building trick). 
find qmake in Qt bin from QTCreator install: default path is /Users/<username>/Qt/5.15.2/clang_64/bin/qmake

then follow koviz install instructions using this qmake from the terminal.

Done!

Using QTCreator to try to build the project ran into some issues, may need to configure QTCreator to get this working.

**Comment by keithvetter** [comment]
Yippee!  There are three active macOS koviz users.  The QRectF is a recent change that would have broken them, so glad you caught this.  This is great!

**Comment by keithvetter** [comment]
I am closing this issue since I think there are MacKoviz users running without issues.  I do hear there are issues with the latest Mac (Feb. 2023) due to OSX using Qt 6.  Once I have Qt 6, I'll write a new issue and tackle it.  It's not really a Mac issue, it's that Qt 6 has some changes that make the koviz build break.  If anybody hits that issue, the current solution is to install and use Qt 5.
