### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [nasa/koviz#9]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [CurveModel](https://github.com/nasa/koviz/blob/b4e1b04f493fd7b0b5144f3e6d740873e7834ed0/libkoviz/curvemodel.cpp#L34 "Destructor for CurveModel")
- [DPProduct](https://github.com/nasa/koviz/blob/945b327448932b20225b663bb18ed988c88692ee/libkoviz/dp.cpp#L39 "Destructor for DPProduct")
- [Thread](https://github.com/nasa/koviz/blob/f2d90966b544d2e801b1b8154578b7ee37637ecd/libkoviz/thread.cpp#L25 "Destructor for Thread")

**Comment by keithvetter** [comment]
Thank you.  I wonder if this is a remnant of programming in C or that something changed in C++ to make deleting a pointer safe.  I'm guessing it's always been safe, so glad to know, thanks.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by keithvetter** [comment]
I'm interested, just hope I don't have to rewrite the whole thing, lol.  This feels like going to the doctor - it's good to go, it's just that I'd rather be surfing.

**Comment by lordmundi** [comment]
that is the best analogy i've ever heard.

**Comment by keithvetter** [comment]
Alright, I pushed a commit that takes out the check, ~10 files in all.  There was one that I didn't take out because it had extra logic around it.  There was another similar check, but it was around malloc/free, so left that alone too.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/nasa/koviz/commit/7fa6c11fadafeea5cf2fa09929932deaf3721310 "Remove if checks on null before delete").


>… There was another similar check, …

:eyes: Further update candidates were left over.
* https://github.com/nasa/koviz/blob/7fa6c11fadafeea5cf2fa09929932deaf3721310/libkoviz/curvemodel.cpp#L40-L47
* https://github.com/nasa/koviz/blob/7fa6c11fadafeea5cf2fa09929932deaf3721310/libkoviz/dptreewidget.cpp#L93-L95

**Comment by keithvetter** [comment]
Thanks.  I didn't take out the check on the curve model because I used free() instead of delete().  Correct me if I can free() without issue.  I'll fix the other one that you caught and push.

**Comment by elfring** [comment]
>Correct me if I can free() without issue.

:thought_balloon: I suggest to [take another look at answers from a known information source](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?").
